$(document).ready(function(){
  $("h2#hmajor").click(function(){
    $("#ulmajor").toggle();
    $("#hhmajor").toggle();
  })
  $("h2#hpersistent").click(function(){
    $("#ulpersistent").toggle();
    $("#hhpersistent").toggle();
  })
  $("h2#hmanic").click(function(){
    $("#hhmanic").toggle();
    $("#hhbipolar").toggle();
  })
  $("#spmanic").click(function(){
    $("#ulmanic").toggle();
  })
  $("#spbipolar").click(function(){
    $("#ulbipolar").toggle();
  })
  $("#hdepressive").click(function(){
    $("#uldepressive").toggle();
    $("#hhdepressive").toggle();
  })
  $("#hperinatal").click(function(){
    $("#hhfeelperinatal").toggle();
    $("#hhsignsperinatal").toggle();
  })
  $("#spfeelperinatal").click(function(){
    $("#ulfeelperinatal").toggle();
  })
  $("#spsignsperinatal").click(function(){
    $("#ulsignsperinatal").toggle();
  })
  $("h2#hseasonal").click(function(){
    $("#hhseasonal").toggle();
    $("#hhfall").toggle();
    $("#pfall").toggle();
    $("#hhspring").toggle();
    $("#pspring").toggle();
    $("#ulseasonal").toggle();
  })
  $("#spfall").click(function(){
    $("#ulfall").toggle();
  })
  $("#spspring").click(function(){
    $("#ulspring").toggle();
  })
  $("h2#hpremenstrual").click(function(){
    $("#ulpremenstrual").toggle();
    $("#hhpremenstrual").toggle();
  })
  $("h2#hsituational").click(function(){
    $("#hheventsituational").toggle();
    $("#hhsituational").toggle();
  })
  $("#spevent").click(function(){
    $("#uleventsituational").toggle();
  })
  $("#spsituational").click(function(){
    $("#ulsituational").toggle();
  })



})
