$("document").ready(function(){
        $("#med-icon").click(function(){
          $("#med-icon").hide();
          $("#medication").show();
        });
        $("#medication").click(function(){
          $("#medication").hide();
          $("#med-icon").show();
        });
      });
      $("document").ready(function(){
        $("#psycho-icon").click(function(){
          $("#psycho-icon").hide();
          $("#psycho").show();
        });
        $("#psycho").click(function(){
          $("#psycho").hide();
          $("#psycho-icon").show();
        });
      });
      $("document").ready(function(){
        $("#hos-icon").click(function(){
          $("#hos-icon").hide();
          $("#hospital").show();
        });
        $("#hospital").click(function(){
          $("#hospital").hide();
          $("#hos-icon").show();
        });
      });
      $("document").ready(function(){
        $("#life-image").click(function(){
          $("#life-image").hide();
          $("#lifestyle").show();
        });
        $("#lifestyle").click(function(){
          $("#lifestyle").hide();
          $("#life-image").show();
        });
      });
      $("document").ready(function(){
        $("#mind-icon").click(function(){
          $("#mind-icon").hide();
          $("#mindbody").show();
        });
        $("#mindbody").click(function(){
          $("#mindbody").hide();
          $("#mind-icon").show();
        });
      });
      $("document").ready(function(){
        $("#cop-image").click(function(){
          $("#cop-image").hide();
          $("#support").show();
        });
        $("#support").click(function(){
          $("#support").hide();
          $("#cop-image").show();
        });
      });
      $("document").ready(function(){
        $("#suicide-image").click(function(){
          $("#suicide-image").hide();
          $("#survovors").show();
        });
        $("#survovors").click(function(){
          $("#survovors").hide();
          $("#suicide-image").show();
        });
      });
      